### ISSUE TITLE
Check validation function

### ISSUE THREAD

**Issue by manueldeljesus** [IHCantabria/NEOPRENE#6]
The validation functions seems to be computing the simulated statistics at a different temporal scale than the one used for fitting, giving the impression that the fits are worse than they really are. We should check why.

**Comment by JavierDiezSierra** [comment]
The problem comes from the  hyperparameter `Seasonality_type`. In the calibration and the simulation yamls this hyperparameter  is now set as "seasonal" and "monthly", respectively. If we want to compare the same observed, fitted and simulated statistics this must be the same.

@navass11, would you please re-run the NSRP notebook with the same argument in both yaml files. We must also modify the notebooks to omit the name of the locations (Bilbao, Sevilleta, ...)

**Comment by navass11** [comment]
@JavierDiezSierra and @manueldeljesus I have already made the changes and re-run the code so that the figure is correct.

**Comment by JavierDiezSierra** [comment]
@navass11 I think it would be better to set `verbose = False` during the calibration to avoid to include unnecessary lines in the notebooks.

**Comment by navass11** [comment]
@manueldeljesus @JavierDiezSierra The notebooks have been updated with the recommendations that were proposed
